stages:
  - test
  - publish

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  untracked: false
  paths:
    - "sbt-cache/.ivy/cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"

default:
  image: registry.mdcatapult.io/informatics/docker-images/ci:scala-v1.1.4

test:
  stage: test
  tags:
    - wopr
  script:
    - sbt +clean coverage +test coverageReport
  coverage: /.*Coverage was \[(\d+.\d+)\%\]/

publish-snapshot:
  stage: publish
  tags:
    - wopr
  script:
    - sbt +publish
  only:
    - develop
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release-master:
  stage: publish
  tags:
    - wopr
  script:
    - /scripts/release.sh -b -r develop
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-master:
  stage: publish
  tags:
    - wopr
  script:
    - sbt +publish
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/